# Generated by Django 3.0.2 on 2020-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='total_publication',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
